import = [
 "~/.config/alacritty/themes/catppuccin_mocha.toml"
]

[shell]
program = "tmux"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Medium" }
size = 13

[window]
dimensions = { columns = 120, lines = 30 }
padding = { x = 8, y = 8}

[keyboard]
bindings = [
  { key = "N", mods = "Control|Shift", action = "SpawnNewInstance" },
  { key = "W", mods = "Control|Shift", action = "Quit" },
  { key = "F11", mods = "Control|Shift", action = "ToggleFullscreen" },
]

[env]
TERM = "alacritty"
